theme: jekyll-theme-minimal
# Site settings
name: Francis
email: xkf1273@gmail.com
author: Francis
github: https://github.com/francisXKF/
permalink: /:year/:month/:day/:title/
site: https://francisxkf.github.io/
baseurl: "/blog"
# Build settings
#markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

# FB:
#   comments :
#     provider : duoshuo
#     duoshuo:
#         short_name : luoyan35714
#     disqus :
#         short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
